language: node_js
node_js:
  - "8"
addons:
  chrome: stable  
before_script:
  - npm install -g codecov
script:
  - npm i --prefix .licia underscore
  - npm link
  - npm run ci
after_success:
  - codecov --disable=gcov
