services:
  test:
    image: node:12.22.12
    volumes:
      - ./:/licia
    working_dir: /licia
    environment:
      - MOD_NAME
    command: ./node_modules/.bin/mocha .licia/test/${MOD_NAME}
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 200M
